# Generated by Django 6.0.6 on 2026-06-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыта в')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта в')),
                ('is_open', models.BooleanField(default=True, verbose_name='Открыта')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['-opened_at'],
            },
        ),
    ]
